#!/bin/bash

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.


ret=100

while [ "$ret" -eq "100" ]
do
	sleep 120
	echo -e "\n`date +%F\ %r` Trying to connect to server... \n"
	apt update > /dev/null 2>&1
	ret=$?
	echo -e "\n`date +%F\ %r` Return value: $ret\n"
done

wall "Check Internet"
