#!/bin/bash

    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.


ret=2

while [[ ${ret} -eq 2 ]]
do
	echo -e "\n`date +%F\ %r` Pinging google.com... "
	ping -c 5 www.google.com 
	ret=$?
    if [[ ${ret} -eq 2 ]]
    then
        echo "Connection failed. Will try again in a minute."
    	sleep 60
    fi
done

if [[ ${ret} -eq 0 ]]
then
    wall "Internet is back!!"
else 
    wall "Internet is probably back."
fi
