#!/bin/bash


    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.

###################################################################################
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/mak/apps/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/mak/apps/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/mak/apps/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/mak/apps/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

COLOR_RED='\e[01;31m'
COLOR_GREEN='\e[01;32m'
COLOR_NONE='\e[0m'

echo -e "\n----------------------------------------------------------------------------"
echo -e "${COLOR_GREEN}Updating Conda${COLOR_NONE}"
echo -e "----------------------------------------------------------------------------\n"
conda update conda -y 
let CONDA_EXIT_CODE="$?"

#echo -e "\nCleaning..."
#conda clean -a -y 

echo -e "\n----------------------------------------------------------------------------"
echo -e "${COLOR_GREEN}Updating Anaconda${COLOR_NONE}"
echo -e "----------------------------------------------------------------------------\n"
conda update anaconda -y 
let ANACONDA_EXIT_CODE="$?"

#echo -e "\nCleaning..."
#conda clean -a -y 

echo -e "\n----------------------------------------------------------------------------"
echo -e "${COLOR_GREEN}Updating All Conda Packages${COLOR_NONE}"
echo -e "----------------------------------------------------------------------------\n"
conda update --all -y
let ALL_EXIT_CODE="$?"

#echo -e "\n----------------------------------------------------------------------------"
#echo -e "${COLOR_GREEN} Cleaning...${COLOR_NONE}"
#echo -e "----------------------------------------------------------------------------\n"
#conda clean -a -y 

echo -e "\n----------------------------------------------------------------------------"
echo -e "${COLOR_GREEN}Operations completed with the following exit codes:${COLOR_NONE}"
echo -e "----------------------------------------------------------------------------\n"

if [[ ${CONDA_EXIT_CODE} -eq 0 ]]
then
    echo -e "${COLOR_GREEN}CONDA   : ${CONDA_EXIT_CODE}${COLOR_NONE}"
else
    echo -e "${COLOR_RED}CONDA   : ${CONDA_EXIT_CODE}${COLOR_NONE}"
fi

if [[ ${ANACONDA_EXIT_CODE} -eq 0 ]]
then
    echo -e "${COLOR_GREEN}ANACONDA: ${ANACONDA_EXIT_CODE}${COLOR_NONE}"
else
    echo -e "${COLOR_RED}ANACONDA: ${ANACONDA_EXIT_CODE}${COLOR_NONE}"
fi

if [[ ${ALL_EXIT_CODE} -eq 0 ]]
then
    echo -e "${COLOR_GREEN}ALL     : ${ALL_EXIT_CODE}${COLOR_NONE}"
else
    echo -e "${COLOR_RED}ALL     : ${ALL_EXIT_CODE}${COLOR_NONE}"
fi

echo -e ""
