#!/bin/bash

COLOR_RED='\e[01;31m'
COLOR_GREEN='\e[01;32m'
COLOR_NONE='\e[0m'

update_env() {
	echo -e "\n-------------------------------------------------------------"
	echo -e "${COLOR_GREEN}Updating ${1}...${COLOR_NONE}"
	echo -e "-------------------------------------------------------------\n"
	conda activate ${1}
	conda update --all -y
	conda deactivate 
	echo -e "${COLOR_GREEN}\nDone${COLOR_NONE}"
	echo -e "-------------------------------------------------------------\n"
}


total_packages=$(conda env list | wc -l)
total_packages=$(( ${total_packages} - 3 ))
envs=( $(conda env list | tail -${total_packages} | head -$(( ${total_packages} - 1 )) | cut -d " " -f 1) ) 
for env in "${envs[@]}"
do
	update_env ${env}
done

echo -e "\n-------------------------------------------------------------"
echo -e "${COLOR_GREEN}Cleaning...${COLOR_NONE}"
echo -e "-------------------------------------------------------------\n"
conda clean -a -y
echo -e "${COLOR_GREEN}\nDone${COLOR_NONE}"
echo -e "-------------------------------------------------------------\n"
