#!/bin/bash


    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.



count=0

download_playlist()
{
	if [ "$count" -gt "20" ]
	then
		echo -e "\nTried ${count} times. Something might be wrong."
		echo -e "Check your internet and the URL and try again."
		return 1
	fi
	count=$(( count+1 )) 

	echo -e "\nDownloading playlist: $1"
	echo -e "\nAttempt: ${count}"
	echo -e "\n"
	youtube-dl $1
	if [ "$?" -ne "0" ]
	then
		echo -e "\nError. Trying again.\n"
		download_playlist "$1"
	fi
}


download_playlist "$1"
wall "Done... maybe?"
