#!/bin/bash


    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.



echo ""
echo "Disconnecting ProtonVPN..."
/usr/bin/protonvpn-cli ks --off
/usr/bin/protonvpn-cli d

echo "Stopping wpa_supplicant..."
service wpa_supplicant stop

echo "Stopping network-manager..."
service network-manager stop 2> /dev/null
service NetworkManager stop 2> /dev/null

echo "Starting network-manager..."
service network-manager start 2> /dev/null
service NetworkManager start 2> /dev/null

echo "Starting wpa_supplicant..."
service wpa_supplicant start
echo ""

echo "Restarting systemd-resolved..."
systemctl restart systemd-resolved.service 
echo ""

## if [ "$(hostname)" == "workhorse" ] && [ "${1}" == "-m" ]  
#if [ "${1}" == "-m" ]  
#then  
#	echo ""
#	echo "Renewing mac..."
#	ifconfig enp1s0 down 2> /dev/null 
#	ifconfig enp3s0 down 2> /dev/null 
#	ifconfig wlp4s0 down 2> /dev/null 
#	ifconfig wlp2s0 down 2> /dev/null 
#	macchanger -r wlp4s0  2> /dev/null 
#	macchanger -r wlp2s0  2> /dev/null 
#	macchanger -r enp1s0  2> /dev/null 
#	macchanger -r enp3s0  2> /dev/null 
#	ifconfig wlp4s0 up 2> /dev/null 
#	ifconfig wlp2s0 up 2> /dev/null 
#	ifconfig enp3s0 up 2> /dev/null 
#	ifconfig enp1s0 up 2> /dev/null 
#	sleep 1 
#fi
#
echo "Disconnecting ProtonVPN..."
/usr/bin/protonvpn-cli d
/usr/bin/protonvpn-cli ks --off
/usr/bin/protonvpn-cli d

