#!/bin/bash


    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.



echo ""
echo "Stopping wpa_supplicant..."
service wpa_supplicant stop

echo "Stopping network-manager..."
service network-manager stop 2> /dev/null
service NetworkManager stop 2> /dev/null

echo "Starting network-manager..."
service network-manager start 2> /dev/null
service NetworkManager start 2> /dev/null

echo "Starting wpa_supplicant..."
service wpa_supplicant start
echo ""

if [ "$(hostname)" == "workhorse" ] && [ "${1}" == "-m" ]  
#if [ "${1}" == "-m" ]  
then  
	echo ""
	echo "Renewing mac..."
	ip link set dev wlo1 down  
	macchanger -r  wlo1 
	ip link set dev  wlo1 up 
	echo -e "\nAfter MAC change:"
	macchanger -s wlo1
fi

