#!/bin/bash


    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.



if [ "$(hostname)" == "workhorse" ] && [ "${1}" == "-m" ]  
then  
	echo ""
	echo "Renewing mac..."
	ifconfig enp3s0 down
	ifconfig wlp4s0 down
	macchanger -r wlp4s0 
	macchanger -r enp3s0 
	ifconfig wlp4s0 up
	ifconfig enp3s0 up
	sleep 1 
fi

echo ""
echo "Stopping wpa_supplicant..."
service wpa_supplicant stop
sleep 1

echo "Stopping network-manager..."
service network-manager stop
sleep 1

echo "Stoping expressvpn..."
service expressvpn stop
sleep 1

echo "Starting expressvpn..."
service expressvpn start
sleep 1

echo "Starting network-manager..."
service network-manager start
sleep 1

echo "Starting wpa_supplicant..."
service wpa_supplicant start
sleep 1
echo ""

