#!/bin/bash

################################################################
# This program is free software: you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

username=$(cat /etc/passwd | grep ":1000:" | cut -d: -f 1)
export DISPLAY=":0"
export XAUTHORITY="/home/${username}/.Xauthority"

command_run=$(basename $(echo $0))
echo "Command that was run: ${command_run}"

echo -e "\n\e[01;31m\bWarning: ${command_run} process is being initiated... \e[01;32m\b Press ^c to cancel. \e[0m\n"
for(( i=2; i>0; i-- )){
    echo -n -e "Time remaining: \e[01;31m\b ${i} \e[0m\b seconds.\r"
    sleep 1
}
echo -e "\e[01;31m\bUser didn't cancel. Running ${command_run}...\e[0m                      "

echo ""
echo "Closing IDEs..."
wmctrl -c py 2>/dev/null &
wmctrl -c ion  2>/dev/null &
wmctrl -c php 2>/dev/null &
wmctrl -c js 2>/dev/null &
wmctrl -c code 2>/dev/null &
wmctrl -c java2>/dev/null &
wmctrl -c json 2>/dev/null &
wmctrl -c html 2>/dev/null &
wmctrl -c css 2>/dev/null &
wmctrl -c xml 2>/dev/null &

echo "Closing applications..."
wmctrl -c brave 2>/dev/null &
wmctrl -c firefox 2>/dev/null &
wmctrl -c tor 2>/dev/null &
wmctrl -c bit 2>/dev/null &
wmctrl -c vlc 2>/dev/null &
wmctrl -c waterfox  2>/dev/null &
wmctrl -c signal  2>/dev/null &
wmctrl -c standard  2>/dev/null &

echo "Killing java..."
killall java 2>/dev/null

dc=$( wmctrl -l | grep -i "dolphin" | wc -l )
while [ ${dc} -gt 0 ] 
do 
	echo "Closing dolphin window #${dc}"
	wmctrl -c dolphin &
	dc=$(( ${dc} - 1 )) 
done
killall caja 2>/dev/null &
killall dolphin 2>/dev/null &

echo "Closing remaining open windows..."
wmctrl -l | tr -s " " |  cut -d" " -f 4 | grep -iv "desktop" | grep -iv "plasma" | grep -iv "${username}" | grep -iv "root" | grep -iv "terminal" | xargs -i wmctrl -c {} &
killall steam >  /dev/null 2>&1

echo "Closing qbittorrent..."
killall -15 qbittorrent 2> /dev/null &

echo "Closing other terminals..."
term=$(tty | cut -d/ -f3,4)
ps -e | grep pts | grep -v ${term} | grep bash | tr -d " " | cut -d p -f 1 | xargs -i kill {}

echo "Unmounting Veracrypt drives..."
sudo /usr/bin/veracrypt -d& 2>/dev/null

echo "Unmounting external drives..."
sudo /usr/bin/umount /media/ext4TB 2>/dev/null
sudo /usr/bin/umount /media/portable2 2>/dev/null
sudo /usr/bin/umount /media/portable1 2>/dev/null

echo "Stopping wpa_supplicant..."
sudo /usr/sbin/service wpa_supplicant stop

echo "Stopping network-manager..."
sudo /usr/sbin/service network-manager stop 2> /dev/null
service NetworkManager stop 2> /dev/null

echo "Stopping Proton vpn..."
/usr/bin/protonvpn-cli d

echo "Stopping packagekit..."
sudo /usr/sbin/service packagekit stop

command_run=$(basename $(echo $0))
if [[ ${command_run} = "reboot" ]]
then
    echo "Rebooting..."
    sudo /usr/sbin/reboot
else 
    echo "Shutting down..."
    sudo /usr/sbin/poweroff
fi

