#!/bin/bash


    # This program is free software: you can redistribute it and/or modify
    # it under the terms of the GNU General Public License as published by
    # the Free Software Foundation, either version 3 of the License, or
    # (at your option) any later version.

    # This program is distributed in the hope that it will be useful,
    # but WITHOUT ANY WARRANTY; without even the implied warranty of
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    # GNU General Public License for more details.

    # You should have received a copy of the GNU General Public License
    # along with this program.  If not, see <https://www.gnu.org/licenses/>.


echo -e "\nAll the .jpg files in the current folder will be shrunk to 3600x(auto) if larger."
echo -n "Are you sure you wish to proceed? (y/n): "
read ans

if [[ "$ans" =~ (y|Y) ]]
then
	echo -e "\nConverting... "
	for file in *.[JjpP][PpnN]*[Gg]
    	do 
		echo "$file"
		newfile="new_$file"
		convert "$file" -resize 3600x3000\> "$newfile"
		rm -f "$file"
		mv "$newfile" "$file"
	done
fi
echo -e "\nDone\n"

