#!/bin/bash

export DISPLAY=":0"
export XAUTHORITY="/home/${username}/.Xauthority"
username=$(cat /etc/passwd | grep ":1000:" | cut -d: -f 1)

echo ""
echo "Closing IDEs..."
wmctrl -c py  2>/dev/null &
wmctrl -c ion  2>/dev/null &
wmctrl -c js  2>/dev/null &
wmctrl -c code  2>/dev/null &
wmctrl -c java 2>/dev/null &
wmctrl -c json  2>/dev/null &
wmctrl -c html  2>/dev/null &
wmctrl -c css  2>/dev/null &
wmctrl -c xml  2>/dev/null &

echo "Closing applications..."
wmctrl -c brave 2>/dev/null &
wmctrl -c firefox 2>/dev/null &
wmctrl -c tor 2>/dev/null &
wmctrl -c bit 2>/dev/null &
wmctrl -c vlc 2>/dev/null &
wmctrl -c waterfox  2>/dev/null &
wmctrl -c signal  2>/dev/null &
wmctrl -c standard  2>/dev/null &
killall slack 2> /dev/null

echo "Killing java..."
killall java 2>/dev/null
sleep 1

dc=$( wmctrl -l | grep -i "dolphin" | wc -l )
while [ ${dc} -gt 0 ] 
do 
	echo "Closing dolphin window #${dc}"
	wmctrl -c dolphin &
	sleep 1
	dc=$(( ${dc} - 1 )) 
done
killall caja 2>/dev/null &
killall dolphin 2>/dev/null &

echo "Closing remaining open windows..."
wmctrl -l | tr -s " " |  cut -d" " -f 4 | grep -iv "desktop" | grep -iv "plasma" | grep -iv "${username}" | grep -iv "root" | grep -iv "terminal" | xargs -i wmctrl -c {} &

echo "Closing qbittorrent"
killall -15 qbittorrent 2> /dev/null  &

echo "Closing other terminals..."
term=$(tty | cut -d/ -f3,4)
ps -e | grep pts | grep -v ${term} | grep bash | tr -d " " | cut -d p -f 1 | xargs -i kill -9 {}

echo "Unmounting Veracrypt drives..."
sudo veracrypt -d&
sleep 1

UP_TO_DATE="Up to date"
NOT_RUNNING="Dropbox isn't running!"

if [[ $(id -u) -eq 1000 ]] 
then 
    while [[ $(dropbox status) != ${UP_TO_DATE} ]]
    do
        dropbox status
        if [[ ${NOT_RUNNING} = $(dropbox status) ]]
        then
            echo "Starting Dropbox... "
            dropbox start > /dev/null 2>&1
        else
            echo "Dropbox is syncing. Will try again after a minute.."
        fi
        sleep 60
    done

else

    while [[ $(sudo -u ${username} -i dropbox status) != ${UP_TO_DATE} ]]
    do
        sudo -u ${username} -i dropbox status
        if [[ ${NOT_RUNNING} = $(sudo -u ${username} -i dropbox status) ]]
        then
            echo "Starting Dropbox... "
            sudo -u ${username} -i sh -c 'unset DISPLAY && dropbox start' > /dev/null 2>&1
        else
            echo "Dropbox is syncing. Will try again after a minute.."
        fi
        sleep 60
    done
fi


echo ""
echo "Running system update"
/usr/local/sbin/update-system -a

echo "Powering down..."
/usr/local/sbin/poweroff
